title: Formalisation of Event Structures
email: git@vikraman.org
description: >
  Formalisation of Event Structures and Causal-Consistency in Lean
github: [metadata]
github_username: vikraman
repository: vikraman/event-structures

plugins:
  - jekyll-github-metadata
